version: "3"
services:
    nginx:
        image: nginx
        ports:
          - 80:80
        volumes:
          - ./config/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
          - app
          
    app:
        build: .
        ports:
          - 8090:8090
        volumes:
          - ./tmp:/tmp
          - ./config/app/conf:/conf